[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ddsp_guitar"
version = "0.1.0"
authors = [{name="Your Name"}]
description = "Guitar-focused DDSP with waveshaper, tonestack, transients"
requires-python = ">=3.10"
dependencies = []
